[package]
name = "server-join-scipt"
description = ""
version = "0.2.0"
edition = "2018"
authors = ["iiTzArcur <arcur@gametools.network>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.15.0"
url = "2.2.2"
serde = "1.0.130"
serde_json = "1.0.68"
serde_derive = "1.0.130"
confy = "0.4.0"
winproc = "0.6.4"
winapi = { version = "0.3.9", features = ["winuser"] }