[package]
name = "seeder-app"
description = ""
version = "0.3.4"
edition = "2018"
authors = ["iiTzArcur <arcur@gametools.network>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
serde_derive = "1.0.130"
confy = "0.4.0"
winproc = "0.6.4"
winapi = { version = "0.3.9", features = ["winuser"] }
ureq = { version = "2.2.0", features = ["json"] }
chrono = "*"
hostname = "^0.3"
system_shutdown = "3.0.0"
urlencoding = "2.1.0"