[package]
name = "server-join-scipt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.17"
tokio = { version = "1.7", features = ["full"] }
tokio-tungstenite = "0.15.0"
url = "2.2.2"
futures-channel = "0.3.17"
serde = "1.0.130"
serde_json = "1.0.68"
serde_derive = "1.0.130"
execute = "0.2.9"
confy = "0.4.0"