name: Build release

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release
      - name: Create folder
        run: |
          mkdir -p build
          cp -R ./target/release/bf1-seeder.exe ./build
          ls ./build

      - name: Deploy 🚀 # deploy to the gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          repository-name: 'community-network/bf1-seeder'
          branch: main # The branch the action should deploy to.
          clean: true # Automatically remove deleted files from the deploy branch
