name: Build release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --bin bf-seeder --release
      - name: Create folder
        run: |
          cp -R ./target/release/bf-seeder.exe ./build
          ls ./build

      - name: Deploy 🚀 # deploy to the gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
        
          personal_token: ${{ secrets.TOKEN }}
          external_repository: community-network/bf1-seeder
          publish_branch: main # default: gh-pages
          publish_dir: ./build
          enable_jekyll: true
